-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."lucumaObservation" add column "perferredTargetId" text
--  null default 'NULL';
