include ".scalafix-common.conf"

Clue.schemaDirs=["schemas/lib/src/clue/resources/lucuma/schemas", "explore/app/src/clue/resources"]
Clue.scalaJSReactReuse=false
Clue.catsShow=false

OrganizeImports.removeUnused = false
# Needed for Scala 3
OrganizeImports.targetDialect = Scala3