packages:
  - schemas
  - explore
  - ui/demo
  - observe/web/client

# https://pnpm.io/settings#minimumreleaseage
# 2 days, in minutes
minimumReleaseAge: 2880

# https://pnpm.io/settings#trustpolicy
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
  - ua-parser-js

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

ignoredBuiltDependencies:
  - protobufjs
