packages:
  - schemas
  - explore
  - observe/web/client
  - ui/demo
  - ui/tests

# https://pnpm.io/settings#minimumreleaseage
# 2 days, in minutes
minimumReleaseAge: 2880

# https://pnpm.io/settings#trustpolicy
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160 # 2 weeks

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

ignoredBuiltDependencies:
  - protobufjs
