scalar UserId

scalar NonEmptyString

input WhereOrderUserId {
  EQ: UserId
  NEQ: UserId
  IN: [UserId!]
  NIN: [UserId!]
  GT: UserId
  LT: UserId
  GTE: UserId
  LTE: UserId
}

input WhereEqUserType {
  EQ: UserType
  NEQ: UserType
  IN: [UserType!]
  NIN: [UserType!]
}

input WhereOptionString {
  IS_NULL: Boolean
  EQ: NonEmptyString
  NEQ: NonEmptyString
  IN: [NonEmptyString!]
  NIN: [NonEmptyString!]
  LIKE: NonEmptyString
  NLIKE: NonEmptyString
  MATCH_CASE: Boolean = true
}

input WhereUserProfile {
  givenName: WhereOptionString
  creditName: WhereOptionString
  familyName: WhereOptionString
  email: WhereOptionString
}

enum Partner {
  AR
  BR
  CA
  CL
  KR
  UH
  US
}

type UserProfile {
  givenName: String
  familyName: String
  creditName: String
  email: String
}

enum UserType {
  GUEST
  STANDARD
  SERVICE
}

input WhereUser {
  IS_NULL: Boolean
  AND: [WhereUser!]
  OR: [WhereUser!]
  NOT: WhereUser
  id: WhereOrderUserId
  type: WhereEqUserType
  orcidId: WhereOptionString
  profile: WhereUserProfile
}

type Query {
  user: User!
  role: Role!
  users(WHERE: WhereUser, OFFSET: UserId, LIMIT: NonNegInt, includeDisabled: Boolean! = false): UserSelectResult!
}

type UserSelectResult {
  matches: [User!]!
  hasMore: Boolean!
}

type Mutation {
  createApiKey(role: RoleId!): String!
  deleteApiKey(id: ApiKeyId!): Boolean!
  addRole(userId: UserId!, roleType: RoleType!, partner: Partner): RoleId!
  deleteRole(roleId: RoleId!): Boolean!
}

type Subscription {
  apiKeyRevocation: ApiKeyId!
}

type User {
  id: UserId!
  orcidId: OrcidId
  profile: UserProfile
  type: UserType!
  enabled: Boolean!
  roles: [Role!]!
  apiKeys: [ApiKey!]!
}

type Role {
  id: RoleId!
  type: RoleType!
  partner: Partner
  user: User!
}

type ApiKey {
  id: ApiKeyId!
  user: User!
  role: Role!
}

scalar OrcidId

scalar RoleId

scalar ApiKeyId

scalar NonNegInt

enum RoleType {
  PI
  NGO
  STAFF
  ADMIN
}