object Versions {
  val acm                    = "0.1.1"
  val boopickle              = "1.5.0"
  val cats                   = "2.13.0"
  val catsEffect             = "3.6.3"
  val catsParse              = "1.1.0"  // new
  val catsRetry              = "3.1.3"
  val catsTime               = "0.6.0"
  val circe                  = "0.14.15"
  val commonsHttp            = "3.1"    // new
  val coulomb                = "0.9.1"
  val clue                   = "0.49.0"
  val crystal                = "0.49.0"
  val discipline             = "1.7.0"
  val disciplineMUnit        = "2.0.0"
  val fs2                    = "3.12.2"
  val fs2Data                = "1.11.0"
  val fs2Dom                 = "0.3.0-M1"
  val geminiLocales          = "0.12.1"
  val giapiScala             = "0.2.3"  // new
  val http4s                 = "0.23.32"
  val http4sDom              = "0.2.12"
  val http4sJdkHttpClient    = "0.10.0" // new
  val http4sScalaXml         = "0.24.0" // new
  val javaTimeJs             = "2.6.0"  // new
  val jUnitInterface         = "0.13.2" // new
  val jwt                    = "11.0.3" // new
  val kittens                = "3.5.0"
  val log4Cats               = "2.7.1"
  val log4CatsLogLevel       = "0.3.1"
  val logback                = "1.5.19" // new
  val lucumaBC               = "0.4.0"
  val lucumaCore             = "0.146.0"
  val lucumaReact            = "0.85.1"
  val lucumaServers          = "0.51.0"
  val lucumaUiSchemas        = "0.174.1"
  val monocle                = "3.3.0"
  val mouse                  = "1.3.2"
  val mUnit                  = "1.2.0"
  val munitDiscipline        = "2.0.0"  // new
  val mUnitCatsEffect        = "2.1.0"
  val mUnitScalacheck        = "1.2.0"
  val natchez                = "0.3.8"  // new
  val natchezHttp4s          = "0.6.1"  // new
  val pprint                 = "0.9.4"  // new
  val pureConfig             = "0.17.9" // new
  val sbtBuildInfo           = "0.13.1"
  val sbtLucuma              = "0.14.4"
  val sbtRevolver            = "0.10.0"
  val scalaCollectionContrib = "0.4.0"
  val scalaJsDom             = "2.8.1"
  val scalaJsReact           = "3.0.0-beta12"
  val scalaXml               = "1.2.0"  // new
  val slf4j                  = "2.0.17" // new
  val unboundId              = "3.2.1"  // new
}
