name: packtracker

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Scala
        uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11        
      - name: Export assets to packtracker
        if: github.event_name == 'pull_request'
        run: |
          sbt -v explore/fullOptJS::webpack
          cd explore/target/scala-2.13/scalajs-bundler/main/
          node --max_old_space_size=2560 node_modules/webpack/bin/webpack --bail --profile --json --config packtracker.webpack.config.js
        env:
          JVM_OPTS: "-Xmx4096M -Xss2M -XX:ReservedCodeCacheSize=256M -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
          PT_COMMIT: ${{ github.event.pull_request.head.sha }}
          PT_PRIOR_COMMIT: ${{ github.event.pull_request.base.sha }}
      - name: Export assets to packtracker merged
        if: github.event_name == 'push'
        run: |
          sbt -v explore/fullOptJS::webpack
          cd explore/target/scala-2.13/scalajs-bundler/main/
          node --max_old_space_size=2560 node_modules/webpack/bin/webpack --bail --profile --json --config packtracker.webpack.config.js
        env:
          JVM_OPTS: "-Xmx4096M -Xss2M -XX:ReservedCodeCacheSize=256M -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
          PT_COMMIT: ${{ github.sha }}
