name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Scala
        uses: olafurpg/setup-scala@v2
        with:
          java-version: 1.8
      - name: Checking your code format
        run: csbt scalafmtCheckAll
      - name: Run tests
        run: csbt headerCheck test:headerCheck test explore/fastOptJS::webpack
